### ISSUE TITLE
Better handlebars error handling

### ISSUE THREAD

**Issue by deniaz** [namics/generator-nitro#43]
... to prevent stuff like that (which ruins BrowserSync's autoreloading):

```javascript
Error: example.html: Parse error on line 9:
...omponent 'header'	</div>	</div>	<di
----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'DATA', got 'INVALID'
   at Object.parseError ([...]/handlebars/compiler/parser.js:150:11)
   at Object.parse ([...]/handlebars/compiler/parser.js:202:22)
   at HandlebarsEnvironment.parse ([...]/handlebars/compiler/base.js:25:30)
   at compileInput ([...]/handlebars/compiler/compiler.js:451:19)
   at ret ([...]/handlebars/compiler/compiler.js:460:18)
   at [...]/hbs/lib/hbs.js:63:19
   at fs.js:334:14
   at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by ernscht** [comment]
I've never seen this error. How can i reproduce this?

**Comment by deniaz** [comment]
```html
<div class="container">
  {{component 'header'
</div>
```

PhpStorm saves files every now and then (e.g. when switching to a different file). BrowserSync then reloads the page. If the Handlebars syntax is not complete/valid, this error is shown.
